config/routes.rb
Rails.application.routes.draw do
  
  
  resources :clinics do
      member do
        get :delete
      end
      resources :professionals do
      member do
        get :delete
        end
      end    
      resources :appointments do
        member do
          get :delete
        end
      end 
       resources :assaigments do
         member do
          get :delete
        end
      end 
      resources :employments do
       member do
          get :delete
        end
      end  
      resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end
  end

  resources :professionals do
    member do
      get :delete
    end
    resources :clinics do
      member do
        get :delete
      end
    end   
    resources :appointments do
        member do
          get :delete
        end
      end 
    resources :assaigments do  # It could be appointments
       member do
         get :delete
       end
    end
    resources :employments do
        member do
          get :delete
        end
     end 
     resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end   
   end
   

 

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :professional
  belongs_to :clinic
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: [:show, :edit, :update, :destroy]

  layout "professional"

  def index
    @employments = Employment.all
  end

  # GET /employments/1
  # GET /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  # POST /employments.json
  def create
    @employment = Employment.new(employment_params)

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: 'Employment was successfully created.' }
        format.json { render :show, status: :created, location: @employment }
      else
        format.html { render :new }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1
  # PATCH/PUT /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to @employment, notice: 'Employment was successfully updated.' }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1
  # DELETE /employments/1.json
  def destroy
    @employment.destroy
    respond_to do |format|
      format.html { redirect_to employments_url, notice: 'Employment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employment_params
      params.require(:employment).permit(:professional_id, :clinic_id, :creator, :is_active)
    end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_for(@employment) do |f| %>
  <% if @employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
      <% @employment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professional_id %><br>
    <%= f.text_field :professional_id %>
  </div>
  <div class="field">
    <%= f.label :clinic_id %><br>
    <%= f.text_field :clinic_id %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employments/delete.html.erb
Skip to content
This repository

    Pull requests
    Issues
    Gist

    @eagt

1
0

    0

mariomc2/timesheet
Code
Issues 0
Pull requests 0
Wiki
Pulse
Graphs
timesheet/app/views/professionals/delete.html.erb
925886d on 23 Feb
Mario Gamez Updated up to centralized current user
18 lines (12 sloc) 543 Bytes
<% @page_title = t(:professional).pluralize(locale) %>

<%= link_to("<< " + t(:return_to), [@current_user, params[:controller]], :class => 'back-link') %>

<div class="professional delete">
	<h2><%= t(:delete) + " " + t(:professional) %></h2>

	<%= form_for([@current_user, @professional], :html => {:method => :delete}) do |f| %>

		<p> <%= t(:delete_message) %> </p>

		<p class="reference-name"><%= @professional.email %></p>

		<div class="form-buttons">
			<%= submit_tag(t(:delete) + " " + t(:professional)) %>
		</div>
	<% end %>
</div>

    Status API Training Shop Blog About 

    © 2016 GitHub, Inc. Terms Privacy Security Contact Help 

app/views/employments/edit.html.erb
<h1>Editing Employment</h1>

<%= render 'form' %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Back', employments_path %>

app/views/employments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employments</h1>

<table>
  <thead>
    <tr>
      <th>Professional</th>
      <th>Clinic</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= employment.professional %></td>
        <td><%= employment.clinic %></td>
        <td><%= employment.creator %></td>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment', new_employment_path %>

app/views/employments/new.html.erb
<h1>New Employment</h1>

<%= render 'form' %>

<%= link_to 'Back', employments_path %>

app/views/employments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professional:</strong>
  <%= @employment.professional %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @employment.clinic %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @employment.creator %>
</p>

<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Back', employments_path %>