config/routes.rb
Rails.application.routes.draw do
  
  
  resources :clinics do
      member do
        get :delete
      end
      resources :professionals do
      member do
        get :delete
        end
      end    
      resources :appointments do
        member do
          get :delete
        end
      end 
       resources :assaigments do
         member do
          get :delete
        end
      end 
      resources :employments do
       member do
          get :delete
        end
      end  
      resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end
  end

  resources :professionals do
    member do
      get :delete
    end
    resources :clinics do
      member do
        get :delete
      end
    end   
    resources :appointments do
        member do
          get :delete
        end
      end 
    resources :assaigments do  # It could be appointments
       member do
         get :delete
       end
    end
    resources :employments do
        member do
          get :delete
        end
     end 
     resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end   
   end
   

 

end

app/models/assaigment.rb
class Assaigment < ActiveRecord::Base
  belongs_to :appointment
  belongs_to :professional
end

app/controllers/assaigments_controller.rb
class AssaigmentsController < ApplicationController
  # before_action :set_assaigment, only: [:show, :edit, :update, :destroy]
  before_action :current_user
  # before_action :set_professional
 
  layout "professional"

 
  # def index
  #   @assaigments = Assaigment.all
  # end

  # # GET /assaigments/1
  # # GET /assaigments/1.json
  # def show
  # end

  # # GET /assaigments/new
  # def new
  #   @assaigment = Assaigment.new
  # end

  # # GET /assaigments/1/edit
  # def edit
  # end

  # # POST /assaigments
  # # POST /assaigments.json
   # def create
   #   @assaignment = @appointment.assaigment.create(params[:assaignment_id])
 
   # end



  #@assaigment = Assaigment.new(assaigment_params)

  #   respond_to do |format|
  #     if @assaigment.save
  #       format.html { redirect_to @assaigment, notice: 'Assaigment was successfully created.' }
  #       format.json { render :show, status: :created, location: @assaigment }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @assaigment.errors, status: :unprocessable_entity }
  #     end
  #   end



  # # PATCH/PUT /assaigments/1
  # # PATCH/PUT /assaigments/1.json
  # def update
  #   respond_to do |format|
  #     if @assaigment.update(assaigment_params)
  #       format.html { redirect_to @assaigment, notice: 'Assaigment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @assaigment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @assaigment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /assaigments/1
  # # DELETE /assaigments/1.json
  # def destroy
  #   @assaigment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to assaigments_url, notice: 'Assaigment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

   private
  #   # Use callbacks to share common setup or constraints between actions.
    # def set_assaigment
    #   @assaigment = Assaigment.find(params[:id])
    # end
# # Method to allow to enter only professionals that belongs to this clinic
#     def set_professional
#        c = Clinic.find(1)
#        p = c.professionals.ids
#        if p.include? professional_id
#             professional_id = :professional_id
#        else
#          puts " can't be added"
#        end
#     end

    def assaignment_params
      params.require(:assaignment).permit(:appointment_id, :professional_id, :creator)
    end
end

    # def set_professional
    #    if is_clinic?
    #     @current_user == @clinic 
    #     @clinic = Clinic.find(params[:id])
    #     p = @clinic.professionals.ids
    #         
    #    else @professional_id = :professional_id
    #    end
    # end


    # def set_appointment
    #  @appointment = Appointment.find(params[:appointment_id])

    # end


  #   # Never trust parameters from the scary internet, only allow the white list through.

app/helpers/assaigments_helper.rb
module AssaigmentsHelper
end

app/views/assaigments/_form.html.erb
<%= form_for(@assaigment) do |f| %>
  <% if @assaigment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assaigment.errors.count, "error") %> prohibited this assaigment from being saved:</h2>

      <ul>
      <% @assaigment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment_id %><br>
    <%= f.text_field :appointment_id %>
  </div>
  <div class="field">
    <%= f.label :professional_id %><br>
    <%= f.text_field :professional_id %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assaigments/edit.html.erb
<h1>Editing Assaigment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assaigment %> |
<%= link_to 'Back', assaigments_path %>

app/views/assaigments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assaigments</h1>

<table>
  <thead>
    <tr>
      <th>Appointment</th>
      <th>Professional</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assaigments.each do |assaigment| %>
      <tr>
        <td><%= assaigment.appointment %></td>
        <td><%= assaigment.professional %></td>
        <td><%= assaigment.creator %></td>
        <td><%= link_to 'Show', assaigment %></td>
        <td><%= link_to 'Edit', edit_assaigment_path(assaigment) %></td>
        <td><%= link_to 'Destroy', assaigment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assaigment', new_assaigment_path %>

app/views/assaigments/new.html.erb
<h1>New Assaigment</h1>

<%= render 'form' %>

<%= link_to 'Back', assaigments_path %>

app/views/assaigments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment:</strong>
  <%= @assaigment.appointment %>
</p>

<p>
  <strong>Professional:</strong>
  <%= @assaigment.professional %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @assaigment.creator %>
</p>

<%= link_to 'Edit', edit_assaigment_path(@assaigment) %> |
<%= link_to 'Back', assaigments_path %>