config/routes.rb
Rails.application.routes.draw do
  
  
  resources :clinics do
      member do
        get :delete
      end
      resources :professionals do
      member do
        get :delete
        end
      end    
      resources :appointments do
        member do
          get :delete
        end
      end 
       resources :assaigments do
         member do
          get :delete
        end
      end 
      resources :employments do
       member do
          get :delete
        end
      end  
      resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end
  end

  resources :professionals do
    member do
      get :delete
    end
    resources :clinics do
      member do
        get :delete
      end
    end   
    resources :appointments do
        member do
          get :delete
        end
      end 
    resources :assaigments do  # It could be appointments
       member do
         get :delete
       end
    end
    resources :employments do
        member do
          get :delete
        end
     end 
     resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end   
   end
   

 

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :clinic
  has_many :appointments

  has_many :client_professionals
  has_many :clients, through: :client_professionals



end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
	has_many :appointments

	has_many :clients
	
	has_many :employments
	has_many :professionals, through: :employments

	accepts_nested_attributes_for :appointments, :employments

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
   before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :current_user
  protect_from_forgery with: :null_session  # Set to be able to delete appointments with null_session
  

 layout "professional"

 
 def index
  if @is_clinic && params[:professional_id] 
    @clients = Professional.find(params[:professional_id]).clients.where(clinic_id: params[:clinic_id])
    
  elsif !@is_clinic && params[:clinic_id] 
    @clients = @current_user.clients.where(clinic_id: params[:clinic_id])
  else
     @clients = @current_user.clients
  end
 end



  def show
    @client = Client.find(params[:id])
  end



    def new 
      #@appointment = @current_user.appointments.new({:creator => @current_user.name})
       @client = @current_user.clients.new({:creator => @current_user.name})
    end
  
  def create
    begin
        @client = Client.create(client_params)
       @current_user.clients << @client    
       flash[:notice] = "Client #{@client.id} created successfully " 
       redirect_to([@current_user, :clients]) 
      rescue Exception => e # Catch exceptions      
      @client = @current_user.clients.new(client_params)
      flash[:notice] = " Can't be added. " +  e.to_s 
      render ("new")
    end
  end

 def edit
   @client = Client.find(params[:id])
  end

  # PATCH/PUT /clients/1
  def update
    # Find and existing object using form parameters
    @client = Client.find(params[:id])
    # Update the object
    if @client.update_attributes(client_params)
      # If update succeeds, redirect to the index action
      flash[:notice] = " Client #{@client.id} updated successfully " 
      redirect_to([@current_user, @client])
    else
      # If save fails, redisplay the from so user can fix problems
      render('edit')
    end
  end


 def delete
    @client = Client.find(params[:id])
  end

  def destroy
    client = Client.find(params[:id]).destroy
    flash[:notice] = " Client #{@client.id}  destroyed "
    redirect_to([@current_user, :clients])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:clinic_id, :name, :creator, client_profesionals_attributes: [:id, :professional_id, :creator, :_destroy])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="table-responsive">
  <table id="fields_table" class="display responsive" summary="Appointment form fields">
    <tbody>
        <tr>
        <th><%= f.label :Name %></th>
        <td><%= f.text_field :name %></td> 
        </tr> 
        <tr> 
        <th><%= f.label :creator %></th>
        <td><%=  f.text_field :creator %></td>
        </tr>
    </tbody>
  </table>
 </div>
<!-- 
 <%#= simple_form_for(@client) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%#= f.association :clinic %>
    <%#= f.input :name %>
    <%#= f.input :creator %>
  </div>

  <div class="form-actions">
    <%#= f.button :submit %>
  </div>
end %> -->

app/views/clients/delete.html.erb
<% @page_title = "Delete Client" %>

app/views/clients/edit.html.erb
<% @page_title = "Edit Client" %>

<h2>Editing Client</h2>

<%= link_to("<< Return", [@current_user, params[:controller]], :class => 'back-link') %>

<div class="appointments edit">

  <%= form_for([@current_user, @appointment]) do |f| %>
    <%= render(:partial => "form", :locals => {:f => f}) %>
<br>
<br>
<div class="form-buttons">
 <%= submit_tag("Update Appointment") %>
</div>

<%= link_to 'Back to Appointments', [@current_user, params[:controller]] %>
<% end %>
</div>

<!-- <h1>Editing Client</h1>

<%#= render 'form' %>

<%#= link_to 'Show', @client %> |
<%#= link_to 'Back', clients_path %> -->

app/views/clients/index.html.erb
<% @page_title = "Clients " %>
<tr>
   <% if !@is_clinic %>
    <td>
      <h2> Professional <%= (@current_user.name )%></h2>
      <h3>Clients</h3>
    </td>
   <% else %>     
     <td> 
      <h2> Clinic <%= (@current_user.name )%></h2>
      <h3>Clients</h3>
     </td>
    <%end%>
 </tr>

<br>
<br>

 <div class="table-responsive">
            <table class="table table-striped">
  <thead>
    <tr>
      <th>Client Id</th>
      <th>Name</th>
      <th>Created by</th>

<!--       <th>Appointments</th> -->

      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.id %></td>
        <td><%= client.name %></td>
        <td><%= client.creator %></td>
        <!-- 
        <td><%#= client.appointments.size %></td> -->

        <td><%= link_to(t(:show), [@current_user, client], :class => 'action show') %></td>
        <td><%= link_to(t(:edit), [:edit, @current_user, client], :class => 'action edit') %></td>
        <td><%= link_to 'Destroy', [@current_user, client], method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to('New Client', [:new, @current_user, params[:controller].singularize], :class => 'action new') %>  
<br>
 <%#= link_to 'New Appointment', {[new_@current_user_appointment], :class => 'action new'} %>
<%= link_to 'Clinics', clinics_path %>



<%= javascript_tag("$(document).ready( function () {$('#index_table').DataTable({responsive: true, fixedHeader: true});} );") %>

<%= javascript_tag("function filterColumn ( i ) {$('#index_table').DataTable().column( i ).search( $('#col'+i+'_filter').val()).draw();}") %>

<%= javascript_tag("window.onload = function(){$('#index_table').DataTable().column(7).data().unique().sort().each( function ( value ) {select = document.getElementById('col7_filter'), option = null; option = document.createElement('option');option.value = value;option.innerHTML = value;select.appendChild(option);} );$('#index_table').DataTable().column(2).data().unique().sort().each( function ( value ) {select = document.getElementById('col2_filter'), option = null; option = document.createElement('option');option.value = value;option.innerHTML = value;select.appendChild(option);} );};") %>

app/views/clients/new.html.erb
<% @page_title = "New Client" %>


<!-- <h1>New Client</h1>

<%#= render 'form' %>

<%#= link_to 'Back', clients_path %> -->



<%= link_to("<< Return ", [@current_user, params[:controller]], :class => 'back-link') %>

<div class="appointments new">

<br>
<tr>
   <% if @is_clinic %>
    <td>
      <h2><%= (@current_user.name )%></h2>
       <h3> Create New Client  <%#= (@clinic.name )%></h3>
    </td>
   <% else %>
     <td> 
       <h2> Professional <%= (@current_user.name )%></h2>
       <h3> Create New Client <%#= (@clinic.name )%></h3>
     </td>
    <%end%>
 </tr>

<br>
  <%= form_for([@current_user, @client]) do |f| %>
    <%= render(:partial => "form", :locals => {:f => f}) %>
<br>
<br>
    <div class="form-buttons">
      <%= submit_tag(" Create New Client") %>
    </div>
  <% end %>

</div>

app/views/clients/show.html.erb
<% @page_title = "Show Client" %>


<tr>
   <% if @is_clinic %>
    <td>
      <h2> Clinic <%= (@current_user.name )%></h2>
        <h3> Client <%= (@client.name )%></h3>
    </td>
   <% else %>
     <td> 
       <h2> Professional <%= (@current_user.name )%></h2>
        <h3> Client <%= (@client.name )%></h3></td>
    <%end%>
 </tr>

 <div class="table-responsive">
  <table id="show_table" class="display responsive" summary="Appointment details view">

 	<tbody>
      	<br>
			  <tr>	
			  	<th><%= t(:Clinic) %></th>
				<td><%#= @client.clinic.name%></td>  <!-- IF THERE IS CLINIC PUT IT, OTHERWISE DON'T-->
			  </tr>
			  <tr>	
			   <th><%= t(:Name) %></th>
			   <td><%= @client.name%></td>
			  </tr>
			  <tr>	
			   <th><%= t(:Creator) %></th>
			   <td><%= @client.creator%></td>
			  </tr>
			  <tr>	
			   <th><%#= t(:Professional) %></th>
			   <td><%#= @client.professional_ids%></td> <!-- IF THERE IS PROFESSIONAL PUT IT, OTHERWISE DON'T-->
			  </tr>

			  <!-- This will show professional/s names and its/their ID depending on how many professionals are booked for this appointment. This is iterating over an array-->
			  
			 <!--   <tr>	
			   % @appointment.professionals.each do |professional| %> 
			   	<th><%#= "Professional Name:" %></th>
			    <td><%#= professional.name  %></td> 
               	<th><%#= "Professional ID:" %></th>
                <td><%#= professional.id.to_s %></td>
               </tr>            
				% end %>  -->
			
	</tbody>
</table>
<br>
<br>
 <%#= link_to('Appointments', @is_clinic ? [@clinic, :appointments] : [@current_user, :appointments, {:clinic_id => @clinic.id}]) %>
<%= link_to(t(:edit), [:edit, @current_user, @client], :class => 'action edit') %> |
<%= link_to 'Back to Clients', [@current_user, params[:controller]] %>
<%#= link_to('Appointments',  @is_clinic? [@current_user, :appointments, {:professional_id => @professional.id}] : [@professional, :appointments])%> |