config/routes.rb
Rails.application.routes.draw do
  
  
  resources :clinics do
      member do
        get :delete
      end
      resources :professionals do
      member do
        get :delete
        end
      end    
      resources :appointments do
        member do
          get :delete
        end
      end 
       resources :assaigments do
         member do
          get :delete
        end
      end 
      resources :employments do
       member do
          get :delete
        end
      end  
      resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end
  end

  resources :professionals do
    member do
      get :delete
    end
    resources :clinics do
      member do
        get :delete
      end
    end   
    resources :appointments do
        member do
          get :delete
        end
      end 
    resources :assaigments do  # It could be appointments
       member do
         get :delete
       end
    end
    resources :employments do
        member do
          get :delete
        end
     end 
     resources :client_professionals do
      member do
          get :delete
        end
      end 
      resources :clients do
       member do
          get :delete
        end
      end   
   end
   

 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salud</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/layouts/professional.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- NAVIGATION (WINDOW/WEDGE) -->

    <title> Salud | <%= @page_title || "" %></title> 
    <%= stylesheet_link_tag('application', :media => 'all') %>
    <%= javascript_include_tag('application') %>
  </head>

  <body>
<!-- TOP BLACK PART -->

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
       

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%#= link_to("Salud", professionals_path, :class => "navbar-brand") %>

            
       <h4 class = "navbar-brand"> Salud </h4>

          
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
            <li><%#= link_to(t(:company).pluralize(locale), professional_companies_path(@professional)) %></li>
            <li><%#= link_to(t(:client).pluralize(locale), professional_clients_path(:professional_id => "1")) %></li>
            <li><%#= link_to(t(:appointment).pluralize(locale), professional_appointments_path(:professional_id => "1")) %></li>
          </ul>  
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if I18n.locale == I18n.default_locale %>
                
                <%= link_to(image_tag('gb.png', :size => '22x14', :alt => 'gb') + " English", :locale=>'en') %>
              <% else %>
                <%= link_to(image_tag('co.png', :size => '22x14', :alt => 'co') + " Español", :locale=>'es') %>
              <%end%>
            </li>
          </ul>          
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="jumbotron">
          <!--/.Application RB Begins-->

          <h1 class="page-header"><%#= t(:professional).pluralize(locale) %></h1>

    <!-- HOME LINK -->
          <%= link_to @current_user do %>
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
          <% end %>



          <div id="main">
            <% if !flash[:notice].blank? %>
              <div class="notice">
                <%= flash[:notice] %>
              </div>
            <% end %>
            <div id="content">

              <%= yield %>

            </div>
          </div>

          <!--/.Application RB Ends-->
        
        </div>
     
   
    </div>

    

    <div id="footer">
    <!--   <p id="copyright"> &copy; mg.com / MG</p> -->
    </div>
  </body>
</html>